type SearchItem = { slug:string; title:string; description:string; category:string; device:string; problemType:string; summary:string; symptoms:string[]; causes:string[] };
const indexNode = document.getElementById('search-index');
const data = JSON.parse(indexNode?.textContent ?? '[]') as SearchItem[];
const aliases: Record<string,string> = {'와이파이':'wifi','무선인터넷':'wifi','wi-fi':'wifi','블루투스':'bluetooth','저장 공간':'저장공간','컴퓨터':'pc','맥':'mac','느림':'느리','끊김':'끊','안됨':'안될','외장 하드':'외장하드','소리 안남':'소리'};
const normalize = (value:string) => { let text=value.toLowerCase().trim().replace(/[\u2010-\u2015_./]+/g,' ').replace(/\s+/g,' '); Object.entries(aliases).forEach(([from,to]) => { text=text.replaceAll(from,to); }); return text.replace(/\s+/g,''); };
const input = document.querySelector<HTMLInputElement>('#site-search'); const results = document.querySelector<HTMLElement>('[data-results]'); const statusEl = document.querySelector<HTMLElement>('[data-status]'); const empty = document.querySelector<HTMLElement>('[data-empty]'); const suggest = document.querySelector<HTMLElement>('[data-suggest]');
if(input && results && statusEl && empty && suggest) {
  input.value = new URLSearchParams(window.location.search).get('q') ?? '';
  const search = (raw:string) => { const q=normalize(raw); if(!q) return []; return data.map((item,index) => { const title=normalize(item.title), symptoms=normalize(item.symptoms.join(' ')), summary=normalize(item.summary), fields=normalize([item.title,item.description,item.category,item.device,item.problemType,item.summary,...item.causes].join(' ')); let score=0; if(title===q)score=100; else if(title.includes(q))score=70; else if(symptoms.includes(q))score=50; else if(summary.includes(q))score=35; else if(fields.includes(q))score=15; else { const terms=raw.trim().split(/\s+/).map(normalize).filter(Boolean); if(terms.length>1&&terms.every(term=>fields.includes(term)))score=30; } return {...item,score,index}; }).filter(item=>item.score>0).sort((a,b)=>b.score-a.score||a.title.localeCompare(b.title)||a.slug.localeCompare(b.slug)); };
  const render = () => { const found=search(input.value); results.textContent=''; empty.hidden=!input.value.trim()||found.length>0; suggest.hidden=Boolean(input.value.trim()); if(!input.value.trim()){statusEl.textContent='검색어를 입력하면 Guide를 찾습니다.';return;} statusEl.textContent=`${found.length}개의 Guide를 찾았습니다.`; found.forEach(item=>{const card=document.createElement('a');card.className='search-result';card.href=`/guides/${item.slug}/`;const tag=document.createElement('span');tag.className='tag';tag.textContent=`${item.category} · ${item.device}`;const title=document.createElement('h2');title.textContent=item.title;const desc=document.createElement('p');desc.textContent=item.description;card.append(tag,title,desc);results.append(card);}); };
  input.addEventListener('input', render); render();
}
